import { type UserRecord } from "@/components/users/users-types"

export const mockUsers: UserRecord[] = [
  {
    id: "u-101",
    first_name: "Ana",
    last_name: "Beridze",
    username: "aberidze",
    email: "ana.beridze@example.com",
    password: "Pass1234",
    role: "admin",
    status: "active",
    createdAt: "2026-01-12T09:15:00.000Z",
  },
  {
    id: "u-102",
    first_name: "Luka",
    last_name: "Kapanadze",
    username: "lkapanadze",
    email: "luka.kapanadze@example.com",
    password: "Pass1234",
    role: "manager",
    status: "active",
    createdAt: "2026-02-09T11:22:00.000Z",
  },
  {
    id: "u-103",
    first_name: "Mariam",
    last_name: "Gogoladze",
    username: "mgogoladze",
    email: "mariam.gogoladze@example.com",
    password: "Pass1234",
    role: "user",
    status: "inactive",
    createdAt: "2026-03-18T14:05:00.000Z",
  },
  {
    id: "u-104",
    first_name: "Nika",
    last_name: "Tsiklauri",
    username: "ntsiklauri",
    email: "nika.tsiklauri@example.com",
    password: "Pass1234",
    role: "user",
    status: "active",
    createdAt: "2026-04-22T08:40:00.000Z",
  },
  {
    id: "u-105",
    first_name: "Tamo",
    last_name: "Japaridze",
    username: "tjaparidze",
    email: "tamo.japaridze@example.com",
    password: "Pass1234",
    role: "manager",
    status: "inactive",
    createdAt: "2026-05-03T16:35:00.000Z",
  },
]
